@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor USER

USER -[#red]> service_A: GET http://service_B:8081/name
service_A -[#red]> service_B: GET http://service_B:8082/name
service_B -[#red]> service_C: GET http://service_B:8083/name


service_B <[#red]-- service_C: GET http://service_B:8083/name
service_A <[#red]-- service_B: GET http://service_B:8082/name
USER <[#red]-- service_A: GET http://service_B:8081/name

@enduml